railwayMgt/railwayMgt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ticketCRUD.urls')),
    path('admin/', admin.site.urls)
] 

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

railwayMgt/ticketCRUD/urls.py
from django.urls import path
from . import views

app_name = 'ticketCRUD'

urlpatterns = [
  path('', views.Index.as_view(), name='index'),
  path('tickets', views.TicketList.as_view(), name='ticket_list'),
  path('new/', views.TicketCreate.as_view(), name='ticket_new'),
  path('edit/<int:pk>/', views.TicketUpdate.as_view(), name='ticket_edit'),
  path('delete/<int:pk>/', views.TicketDelete.as_view(), name='ticket_delete'),
]

railwayMgt/ticketCRUD/models.py
from django.db import models
from django.urls import reverse
from django import forms


class Ticket(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()
    address = models.TextField()
    city = models.TextField()
    state = models.TextField()

    travelDate = models.DateField()
    source = models.TextField()
    dest = models.TextField()

    train = models.TextField()
    price = models.FloatField()

    intTravel = models.BooleanField()
    setuStatus = models.CharField(max_length=50)
    report = models.BooleanField()

    ## Images
    image=models.ImageField(null=True,blank=True,upload_to="images/")
   
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ticketCRUD:ticket_edit', kwargs={'pk': self.pk})
    

railwayMgt/ticketCRUD/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Ticket
from django.shortcuts import render


class Index(TemplateView):
    template_name = 'ticketCRUD/index.html'


class TicketList(ListView):
    model = Ticket
    template_name = 'ticketCRUD/ticket_list.html'

class TicketCreate(CreateView):
    model = Ticket
    fields = ['name', 'age','address','city','state','travelDate','source','dest','train','price','intTravel','setuStatus','report','image']
    template_name = 'ticketCRUD/ticket_form.html'
    success_url = reverse_lazy('ticketCRUD:ticket_list')

class TicketUpdate(UpdateView):
    model = Ticket
    fields = ['name', 'age','address','city','state','travelDate','source','dest','train','price','intTravel','setuStatus','report','image']
    template_name = 'ticketCRUD/ticket_edit.html'
    success_url = reverse_lazy('ticketCRUD:ticket_list')


class TicketDelete(DeleteView):
    model = Ticket
    template_name = 'ticketCRUD/ticket_confirm_delete.html'
    success_url = reverse_lazy('ticketCRUD:ticket_list')

railwayMgt/ticketCRUD/templates/ticketCRUD/home.html
{% load static %}

<html>
<head>
    <title>Railway Management System</title>


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">  
    <link href="{% static 'css/style.css' %}" rel="stylesheet">  
    <script src="{% static 'js/bootstrap.min.js' %}"></script>  
</head>
<body >
  
    <div id="header">
        <h1 class="text-center"><a href="/">Railway Management System</a></h1>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="footer">
    </div>
</body>
</html>

railwayMgt/ticketCRUD/templates/ticketCRUD/index.html
 {% extends "ticketCRUD/home.html" %}

{% block content %}

<h2 class="text-center"><a href="#">Main Menu</a></h2>
<div class="row py-5">
  <div class="col-sm-6 d-flex justify-content-center">
    <div class="card text-center " style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title py-3">Show Tickets</h5>
        <a href="{% url 'ticketCRUD:ticket_list' %}" class="btn btn-primary col-sm-12 d-flex justify-content-center ">Show</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6 d-flex justify-content-center">
    <div class="card text-center" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title py-3">Create New Ticket</h5>
        <a href="{% url 'ticketCRUD:ticket_new' %}" class="btn btn-primary col-sm-12 d-flex justify-content-center">Create</a>
      </div>
    </div>
  </div>
</div>

<h2 class="text-center"><a href="#">Coded By:</a></h2>
<h2 class="text-center"><a href="#">Rajat Kaushik</a></h2>
<h3 class="text-center"><a href="#">BT18GCS096</a></h3>
<h3 class="text-center"><a href="#">Section: C7</a></h3>

{% endblock %}

railwayMgt/ticketCRUD/templates/ticketCRUD/ticket_confirm_delete.html
 {% extends "ticketCRUD/home.html" %}

{% block content %}

      
<h2 class="text-center"><a href="#">Ticket Deletion</a></h2>
 <h2 class="text-center"><a href="{% url 'ticketCRUD:ticket_list' %}" class="btn btn-primary ">Show Tickets</a>
    <a href="{% url 'ticketCRUD:ticket_new' %}" class="btn btn-primary ">Create New Ticket</a>
    <a href="/" class="btn btn-secondary ">Main Menu</a>
</h2>

<form method="post">{% csrf_token %}
<div class="row py-5">
    <div class="col-sm-12 d-flex justify-content-center">
      <div class="card text-center " style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Are you sure you want to delete</h5>
          <p class="card-text"><b>Ticket No: </b> {{ object.id }} <b> <br> named after </b> {{ object.name }}</p>
          <button class="btn btn-danger col-sm-12 d-flex justify-content-center" type="submit" value="Delete">Delete</button>
        </div>
      </div>
    </div>
   
  </div>
</form>
{% endblock %}

railwayMgt/ticketCRUD/templates/ticketCRUD/ticket_edit.html
 {% extends "ticketCRUD/home.html" %}

 {% block content %}

 <h2 class="text-center"><a href="{% url 'ticketCRUD:ticket_list' %}" class="btn btn-primary ">Show Tickets</a>
     <a href="/" class="btn btn-secondary ">Main Menu</a></h2>

 <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}

     <div class="row py-3">
         <div class="col-sm-12 d-flex justify-content-center">
             <div class="card  " style="width: 25rem;">
                 <div class="card-body bg-secondary ">
                     <h5 class="card-title text-center"> Ticket Edit: {{ ticket.id }} </h5>
                     <p class="card-text"><br>
                         <p>
                            <b><label for="id_name" class="form-label">{{form.name.label_tag}}</label></b>
                             <input id="id_name" type="text" name="name" class="form-control" value={{form.name.value}} required>
                             
                         </p>

                         <p>
                            <b><label for="id_age" class="form-label">Age:</label></b>
                             <input id="id_age" type="number" name="age" class="form-control" value={{form.age.value}} required>
                         </p>
                         <p>
                            <b><label for="id_address" class="form-label">Address:</label></b>
                             <textarea  id="id_address" name="address" rows="2" cols="20" class="form-control" value=`ticket.address` required>{{form.address.value}}</textarea>
                         </p>

                         <p>
                            <b> <label for="id_city" class="form-label">Choose City: </label></b>

                             <select name="city" id="id_city" class="form-select" required>
                                 <option value="Delhi">Delhi</option>
                                 <option value="Mumbai">Mumbai</option>
                                 <option value="Chennai">Chennai</option>
                                 <option value="Kolkata">Kolkata</option>
                             </select>
                         </p>

                         <p>
                            <b> <label for="id_state" class="form-label">Choose State: </label></b>

                             <select name="state" id="id_state" class="form-select"  required>
                                 <option value="Delhi">Delhi</option>
                                 <option value="Maharashtra">Maharashtra</option>
                                 <option value="Tamil Nadu">Tamil Nadu</option>
                                 <option value="Kolkata">West Bengal</option>
                             </select>
                         </p>

                         <p>
                            <b> <label for="id_travelDate" class="form-label">Travelling Date: </label></b>
                             <input id="id_travelDate" type="date" name="travelDate" class="form-control" required>
                         </p>

                         <p>
                            <b>  <label for="id_source" class="form-label">Choose From Station: </label></b>

                             <select name="source" id="id_source" class="form-select" value={{form.source.value}} required>
                                 <option value="Delhi">Delhi</option>
                                 <option value="Mumbai">Mumbai</option>
                                 <option value="Chennai">Chennai</option>
                                 <option value="Kolkata">Kolkata</option>
                             </select>
                         </p>

                         <p>
                            <b>  <label for="id_dest" class="form-label">Choose Destination Station: </label></b>

                             <select name="dest" id="id_dest" class="form-select"  required>
                                 <option value="Delhi">Delhi</option>
                                 <option value="Mumbai">Mumbai</option>
                                 <option value="Chennai">Chennai</option>
                                 <option value="Kolkata">Kolkata</option>
                             </select>
                         </p>

                         <p>
                            <b>  <label for="id_train" class="form-label">Choose Train: </label></b>

                             <select name="train" id="id_train" class="form-select" required>
                                 <option value="Rajdhani">Rajdhani</option>
                                 <option value="Shatabdi">Shatabdi</option>
                                 <option value="Bullet">Bullet</option>
                             </select>
                         </p>

                         <p>
                            <b> <label for="id_price" class="form-label">Choose Price: </label></b>

                             <select name="price" id="id_price" class="form-select" required>
                                 <option value=3000.50>AC-1: Rs: 3000.50 </option>
                                 <option value=2000.50>AC-2: Rs: 2000.50 </option>
                                 <option value=1000.50>AC-3: Rs: 1000.50 </option>

                             </select>
                         </p>

                         <p>
                            <b> <label for="id_intTravel" class="form-label">International Travel:</label></b>
                             <input id="id_intTravel" type="checkbox" name="intTravel"  class="form-check-input" >
                         </p>

                         <p>
                            <b> <label class="form-label">Aarogya Setu App Status: </label></b>

                             <input type="radio" id="id_setuStatus" name="setuStatus" value="Green" class="form-check-input" required>
                             <label for="id_setuStatus">Green</label>

                             <input type="radio" id="id_setuStatus" name="setuStatus" value="Red" class="form-check-input" required>
                             <label for="id_setuStatus">Red</label>

                         </p>

                         <p>
                            <b>  <label for="id_report" class="form-label">Carrying RT-PCR Report</label></b>
                             <input id="id_report" type="checkbox" name="report" class="form-check-input" >
                         </p>

                         <p>
                            <b> <label for="id_image" class="form-label">Upload Aadhar Image:</label></b>
                            <p >{{form.image.as_widget}}</p>
                            <!-- <input type="file" id="id_image" name="image" class="form-control" required> -->
                         </p>

                         <!-- {{ form.as_ul}} -->
                         <button class="btn btn-success col-sm-12 d-flex justify-content-center" type="submit"
                             value="Submit">Submit</button>


                 </div>
             </div>
         </div>

     </div>
 </form>
 {% endblock %}

railwayMgt/ticketCRUD/templates/ticketCRUD/ticket_form.html
 {% extends "ticketCRUD/home.html" %}

 {% block content %}

 <h2 class="text-center"><a href="{% url 'ticketCRUD:ticket_list' %}" class="btn btn-primary ">Show Tickets</a>
     <a href="/" class="btn btn-secondary ">Main Menu</a></h2>

 <form method="post">{% csrf_token %}

     <div class="row py-3">
         <div class="col-sm-12 d-flex justify-content-center">
             <div class="card  " style="width: 25rem;">
                 <div class="card-body">
                     <h5 class="card-title text-center"> Ticket </h5>
                     <p class="card-text"><br>
                         <p>
                             <label for="id_name">Name:</label>
                             <input id="id_name" type="text" name="name" required>
                         </p>
                         <p>
                             <label for="id_age">Age:</label>
                             <input id="id_age" type="number" name="age" required>
                         </p>
                         <p>
                             <label for="id_address">Address:</label>
                             <textarea id="id_address" name="address" rows="2" cols="20" required></textarea>
                         </p>

                         <p>
                             <label for="id_city">Choose City: </label>

                             <select name="city" id="id_city">
                                 <option value="Delhi">Delhi</option>
                                 <option value="Mumbai">Mumbai</option>
                                 <option value="Chennai">Chennai</option>
                                 <option value="Kolkata">Kolkata</option>
                             </select>
                         </p>

                         <p>
                             <label for="id_state">Choose State: </label>

                             <select name="state" id="id_state">
                                 <option value="Delhi">Delhi</option>
                                 <option value="Maharashtra">Maharashtra</option>
                                 <option value="Tamil Nadu">Tamil Nadu</option>
                                 <option value="Kolkata">West Bengal</option>
                             </select>
                         </p>

                         <p>
                             <label for="id_travelDate">Travelling Date: </label>
                             <input id="id_travelDate" type="date" name="travelDate" required>
                         </p>

                         <p>
                             <label for="id_source">Choose From Station: </label>

                             <select name="source" id="id_source">
                                 <option value="Delhi">Delhi</option>
                                 <option value="Mumbai">Mumbai</option>
                                 <option value="Chennai">Chennai</option>
                                 <option value="Kolkata">Kolkata</option>
                             </select>
                         </p>

                         <p>
                             <label for="id_dest">Choose Destination Station: </label>

                             <select name="dest" id="id_dest">
                                 <option value="Delhi">Delhi</option>
                                 <option value="Mumbai">Mumbai</option>
                                 <option value="Chennai">Chennai</option>
                                 <option value="Kolkata">Kolkata</option>
                             </select>
                         </p>

                         <p>
                             <label for="id_train">Choose Train: </label>

                             <select name="train" id="id_train">
                                 <option value="Rajdhani">Rajdhani</option>
                                 <option value="Shatabdi">Shatabdi</option>
                                 <option value="Bullet">Bullet</option>
                             </select>
                         </p>

                         <p>
                             <label for="id_price">Choose Price: </label>

                             <select name="price" id="id_price">
                                 <option value=3000.50>AC-1: Rs: 3000.50 </option>
                                 <option value=2000.50>AC-2: Rs: 2000.50 </option>
                                 <option value=1000.50>AC-3: Rs: 1000.50 </option>

                             </select>
                         </p>

                         <p>
                             <label for="id_intTravel">International Travel:</label>
                             <input id="id_intTravel" type="checkbox" name="intTravel">
                         </p>

                         <p>
                             <label>Aarogya Setu App Status: </label>

                             <input type="radio" id="id_setuStatus" name="setuStatus" value="Green">
                             <label for="id_setuStatus">Green</label>

                             <input type="radio" id="id_setuStatus" name="setuStatus" value="Red">
                             <label for="id_setuStatus">Red</label>

                         </p>

                         <p>
                             <label for="id_report">Carrying RT-PCR Report</label>
                             <input id="id_report" type="checkbox" name="report">
                         </p>

                      

                         <button class="btn btn-success col-sm-12 d-flex justify-content-center" type="submit"
                             value="Submit">Submit</button>


                 </div>
             </div>
         </div>

     </div>
 </form>
 {% endblock %}

railwayMgt/ticketCRUD/templates/ticketCRUD/ticket_list.html
{% extends "ticketCRUD/home.html" %}

{% block content %}


<h2 class="text-center"><a href="{% url 'ticketCRUD:ticket_list' %}">Tickets</a></h2>
<h2 class="text-center"><a href="{% url 'ticketCRUD:ticket_new' %}" class="btn btn-primary ">Create New Ticket</a>
    <a href="/" class="btn btn-secondary ">Main Menu</a></h2>
<ul>



    <div class="row py-3">
        {% for ticket in object_list %}
        <div class="col-sm-3 d-flex justify-content-center py-3">
            <div class="card  " style="width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title text-center"> Ticket Number : {{ ticket.id }} </h5>
                    <table class="table table-hover">
                        <tr>
                            <td class="table-light"><b>Passenger Name:</b></td>
                            <td class="table-light">{{ ticket.name }}</td>
                        </tr>

                        <tr>
                            <td class="table-light"><b>Passenger Age:</b></td>
                            <td class="table-light">{{ ticket.age }} Years</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Address</b></td>
                            <td class="table-light">{{ ticket.address }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>City</b></td>
                            <td class="table-light">{{ ticket.city }} </td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>State</b></td>
                            <td class="table-light">{{ ticket.state }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Travel Date</b></td>
                            <td class="table-light">{{ ticket.travelDate }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Source Station</b></td>
                            <td class="table-light">{{ ticket.source }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Destination Station</b></td>
                            <td class="table-light">{{ ticket.dest }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Train</b></td>
                            <td class="table-light">{{ ticket.train }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Price</b></td>
                            <td class="table-light">{{ ticket.price }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Internation Travel</b></td>
                            <td class="table-light">{{ ticket.intTravel }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Aarogya Setu Status</b></td>
                            <td class="table-light">{{ ticket.setuStatus }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Carrying RT-PCR Report:</b></td>
                            <td class="table-light">{{ ticket.report }}</td>
                        </tr>
                        <tr>
                            <td class="table-light"><b>Aadhar Image: </b></td>
                            <td class="table-light"><b></b></td>
                        </tr>
                        

                    </table>
                    <img src="media/{{ticket.image}}" alt="" height="200px" width="285px" />
                    <hr>

                    <a href="{% url 'ticketCRUD:ticket_edit' ticket.id %}"
                        class="btn btn-primary col-sm-12 d-flex justify-content-center ">Edit</a>
                    <hr>
                    <a href="{% url 'ticketCRUD:ticket_delete' ticket.id %}"
                        class="btn btn-danger col-sm-12 d-flex justify-content-center">Delete</a>


                </div>
            </div>
        </div>
        {% endfor %}
    </div>



</ul>



{% endblock %}